version: 2.1

jobs:
  Build-Documentation:
    docker:
      - image: cimg/base:edge-22.04
    steps:
      - add_ssh_keys:
          fingerprints:
            c2:79:07:18:78:47:c7:82:a2:99:9f:ad:5c:f0:0e:c5
      - add_ssh_keys:
          fingerprints:
             3e:95:52:20:45:2a:ec:bc:59:74:91:fe:d1:36:c5:bb

      - checkout 
      - run:
          name: Collect the original Repo for the docs.
          command: sudo git config --global user.email "40668522+RealTimeChris@users.noreply.github.com " && sudo git config --global user.name "realtimechris" && sudo git clone https://realtimechris:${PERSONAL_ACCESS_TOKEN}@github.com/realtimechris/DiscordCoreAPI-Docs --depth=1
      - run:
          name: Download and install Doxygen.
          command: sudo apt-get install doxygen && sudo apt install graphviz && sudo apt-get install openssh-client

      - run:
          name: Collect the documentation and generate it.
          command: sudo git clone https://github.com/RealTimeChris/DiscordCoreAPI --depth=1 && 
                    cd DiscordCoreAPI/Documentation/Doxygen && 
                    sudo doxygen

      #- run:
       #     name: Add AWS to known hosts.
            #command: sudo mkdir -p ~/.ssh
                    #sudo echo 'ubuntu@ec2-18-188-35-140.us-east-2.compute.amazonaws.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEZdkfp1BtUDcb8mIoIFBOw7uKNEKdirvqnRZ8mxF0fB' > ~/.ssh/known_hosts &&
                    #sudo echo 'ubuntu@ec2-18-188-35-140.us-east-2.compute.amazonaws.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEZdkfp1BtUDcb8mIoIFBOw7uKNEKdirvqnRZ8mxF0fB' > ~/.ssh/authorized_keys
                        

      - run:
          name: Commit and push.
          command: cd DiscordCoreAPI-Docs && 
                    sudo git add . && 
                    sudo git commit -m "Updates!" && 
                    sudo git push origin main || true
      - run:
          name: Clone the data over to the web server.
          command: sudo echo ${AWS_KEY} >TheRealKey.pem &&
                    sudo ssh -o BatchMode=yes -o StrictHostKeyChecking=no ubuntu@ec2-18-224-43-180.us-east-2.compute.amazonaws.com &&
                    sudo ssh -i TheRealKey.pem ubuntu@ec2-18-224-43-180.us-east-2.compute.amazonaws.com &&
                    cd /var/www &&
                    sudo rm -rf discordcoreapi &&
                    sudo git clone https://github.com/RealTimeChris/DiscordCoreAPI-Docs --depth=1 ./discordcoreapi
            
            

workflows:
  Build-DiscordCoreAPI:
    jobs:
      - Build-Documentation

