version: 2.1

jobs:
  Build-Documentation:
    docker:
      - image: cimg/base:edge-22.04
    steps:
      - add_ssh_keys:
          fingerprints:
             60:1a:f1:b6:e2:37:a3:7c:58:f8:6f:fe:fe:ff:0d:21

      - checkout 
      - run:
          name: Collect the original Repo for the docs.
          command: sudo git config --global user.email "40668522+RealTimeChris@users.noreply.github.com " && sudo git config --global user.name "realtimechris" && sudo git clone https://realtimechris:${PERSONAL_ACCESS_TOKEN}@github.com/realtimechris/DiscordCoreAPI-Docs --depth=1
      - run:
          name: Download and install Doxygen.
          command: sudo apt-get install doxygen && sudo apt install graphviz && sudo apt-get install openssh-client

      - run:
          name: Collect the documentation and generate it.
          command: sudo git clone https://github.com/RealTimeChris/DiscordCoreAPI --depth=1 && 
                    cd DiscordCoreAPI/Documentation/Doxygen && 
                    sudo doxygen

      #- run:
       #     name: Add AWS to known hosts.
            #command: sudo mkdir -p ~/.ssh
                    #sudo echo 'uubuntu@ec2-18-224-43-180.us-east-2.compute.amazonaws.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOTCp474/vxnF5AfMdBZ+d/s+4JL3EeB4AQtORBiu3dK' > ~/.ssh/known_hosts &&
                    #sudo echo 'ubuntu@ec2-18-224-43-180.us-east-2.compute.amazonaws.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzOhOTL/6IwyUAtLYvj6F9QLxbrBTN7Q68lX/ffFJ2IBAm1POl+bnDPbgIYzxpAy++fzAyRuQRWVs/gAQ2WLS+Fzstu95121aMiU9Vrrgd4c0ioRjuHI+ik4I7HQCtXTfoSFLq+dL1bAYz5wjlYsFc3RFj6bTFsrKKHpplwkZtF8v9+7HJkiR/LYDWdX32ChBesGaNj4LEj5sLs/rhjRK8q5xjQc+yE587QI9vX+NDwEPb9D9B3NBx0KsxZ3ey6COOzK0jq0eav49nU8rIxLguATg9k0yh4yZVi/aJbgc5MNpvchPTme9R6IQ3GcmjmOPLVwo+uhyk1m8hYUqCT4nUimuSItlIMawP8m9LuaU5FTYHYc9f7wrkQndrB1rGTPyOuBq0n4VPNsFM6PQ6ZoiJ+HJHxSn/buOQm83KWmRvELLTfjKOjhtsejv5vrzWLgYd1rJWdt8PxcWN8/SUnyP27xEvcJ7aL9jBI4iNLxmVAnjthtzQ0V5xLHX/v0LByEc=' > ~/.ssh/authorized_keys
                        
      - run:
          name: "Save the private key."
          command: echo "$AWS_KEY >> $THE_REAL_KEY"

      - run:
          name: Commit and push.
          command: cd DiscordCoreAPI-Docs && 
                   sudo git add . && 
                   sudo git commit -m "Updates!" && 
                   sudo git push origin main || true
      - run:
          name: Clone the data over to the web server.
          command: cd /home &&
                   find "./" type d "/.ssh" &&
                   dir &&
                   sudo ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOTCp474/vxnF5AfMdBZ+d/s+4JL3EeB4AQtORBiu3dK >> /home/*/.ssh/authorized_keys &&
                   sudo ssh -o BatchMode=yes -o StrictHostKeyChecking=no ubuntu@ec2-3-144-188-157.us-east-2.compute.amazonaws.com &&
                   sudo ssh -i $THE_REAL_KEY ubuntu@ec2-3-144-188-157.us-east-2.compute.amazonaws.com &&                    
                   cd /var/www &&
                   sudo rm -rf discordcoreapi &&
                   sudo git clone https://github.com/RealTimeChris/DiscordCoreAPI-Docs --depth=1 ./discordcoreapi
            

workflows:
  Build-DiscordCoreAPI:
    jobs:
      - Build-Documentation

