version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:edge-22.04

    steps:
      - checkout
      - run:
          name: Installing vcpkg.
          command: 'sudo git clone https://github.com/Microsoft/vcpkg ./vcpkg && cd ./vcpkg && sudo ./bootstrap-vcpkg.sh'
      - run:
          name: Copying over Vcpkg files.
          command: 'sudo cp -a -v Vcpkg vcpkg'
      - run:
          name: Installing dependencies.
          command: 'sudo apt-get install nasm && sudo apt-get install bison  && cd ./vcpkg && sudo ./vcpkg install discordcoreapi:x64-linux'

