version: 2.1

jobs: # basic units of work in a run
  Build-Documentation:
    docker: # use the Docker executor
      # CircleCI node images available at: https://hub.docker.com/r/circleci/node/
      - image: cimg/base:edge-22.04
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      # Run a step to setup an environment variable
      # Redirect MY_ENV_VAR into $BASH_ENV
      - run:
          name: Checkout github pages repository
          command: git config --global user.email "40668522+RealTimeChris@users.noreply.github.com" && git config --global user.name "realtimechris"
      - run: # print the name of the branch we're on
          name: Download and install Doxygen.
          command: sudo apt-get install doxygen && sudo apt install graphviz
      # Run another step, the same as above; note that you can
      # invoke environment variable without curly braces.
      - run:
          name: Collect the original Repo for the docs.
          command: git clone https://github.com/RealTimeChris/DiscordCoreAPI-Docs
      - run:
          name: Collect the documentation and generate it.
          command: |
            sudo git clone https://github.com/RealTimeChris/DiscordCoreAPI --depth=1
            cd DiscordCoreAPI/Documentation/Doxygen
            sudo doxygen
      - run:
          name: commit and push
          command: | 
            cd DiscordCoreAPI-Docs
            sudo git config --global --add safe.directory /home/circleci/project/DiscordCoreAPI-Docs
            sudo git add .
            sudo git commit -m "Updates!"
            sudo git push origin main:realtimechris${PERSONAL_ACCESS_TOKEN}
      - run:
          name: Clone the data over to the web server.
          command: |
            sudo nano TheRealKey.pem ${{ secrets.AWS_KEY }}
            ssh -i "./TheRealKey.pem" ubuntu@ec2-3-144-10-105.us-east-2.compute.amazonaws.com
            cd /var/www
            sudo rm -rf discordcoreapi
            sudo git clone https://github.com/RealTimeChris/DiscordCoreAPI-Docs --depth=1 ./discordcoreapi

workflows: # a single workflow with a single job called build
  build:
    jobs:
      - Build-Documentation

