version: 2.1

jobs:

  Build-DiscordCoreAPI:
    machine:
        image: ubuntu-2204:2022.04.1
    resource_class: large
    steps:
      - checkout
      - run:
           name: Download and install vcpkg as well as other dependencies.
           command: sudo apt-get install nasm && 
                    sudo git clone https://github.com/Microsoft/vcpkg --depth=1 &&
                    sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && 
                    sudo apt install -y g++-11 &&
                    cd vcpkg &&
                    sudo ./bootstrap-vcpkg.sh

      - run:
          name: Copy over the current portfile.
          command: sudo git config --global user.email "40668522+RealTimeChris@users.noreply.github.com" &&
                   sudo git config --global user.name "realtimechris" &&
                   sudo git clone https://realtimechris:${PERSONAL_ACCESS_TOKEN}@github.com/realtimechris/DiscordCoreAPI --depth=1

      #- run:
         #name: Update the portfile.
         #command: sudo chmod 600 ./DiscordCoreAPI/Vcpkg/ports/discordcoreapi/portfile.cmake

      #- run:
         #name: Update the portfile.
         #command: sudo bash -c "cat ./DiscordCoreAPI/.github/Raw-Files/portfile-first-half.cmake > ./DiscordCoreAPI/Vcpkg/ports/discordcoreapi/portfile.cmake"

      - run:
         name: Update the portfile.
         command: cd DiscordCoreAPI &&
                  sudo cp -v -R ./.github/Raw-Files/portfile-first-half.cmake /home/circleci/project/vcpkg/ports/discordcoreapi/portfile-first-half-new.cmake
                  sudo git rev-parse HEAD | sudo tee /home/circleci/project/vcpkg/ports/discordcoreapi/portfile-first-half-new.cmake -a

      - run:
         name: Update the portfile.
         command: sudo bash -c "cat ./DiscordCoreAPI/.github/Raw-Files/portfile-second-half.cmake >> /home/circleci/project/vcpkg/ports/discordcoreapi/portfile-first-half-new.cmake" &&
                  sudo cp -v -R ./DiscordCoreAPI/Vcpkg/* /home/circleci/project/vcpkg &&
                  sudo cp -v -R /home/circleci/project/vcpkg/ports/discordcoreapi/portfile-first-half-new.cmake /home/circleci/project/vcpkg/ports/discordcoreapi/portfile.cmake &&
                  sudo git config --global --add safe.directory /home/circleci/project/DiscordCoreAPI &&
                  sudo /home/circleci/project/vcpkg/vcpkg install discordcoreapi:x64-linux | sudo tee InstallOutput.txt || true

      - run:
         name:  Update the portfile and download/install the library.
         command: sed -i '/Actual hash/,$!d' InstallOutput.txt &&
                  sed -i 's/^.....................//' InstallOutput.txt &&
                  sed -i '2,250d' InstallOutput.txt &&
                  truncate -s -3 InstallOutput.txt &&
                  sed -i '12,25d' /home/circleci/project/vcpkg/ports/discordcoreapi/portfile-first-half-new.cmake &&
                  truncate -s -54 /home/circleci/project/vcpkg/ports/discordcoreapi/portfile-first-half-new.cmake &&
                  sudo bash -c "head -c 241 ./DiscordCoreAPI/Vcpkg/ports/discordcoreapi/portfile.cmake > /home/circleci/project/vcpkg/ports/discordcoreapi/portfile-first-half-new.cmake"  &&
                  sudo bash -c "echo $'\n        SHA512' >> /home/circleci/project/vcpkg/ports/discordcoreapi/portfile-first-half-new.cmake"  &&
                  sudo bash -c "cat InstallOutput.txt >> /home/circleci/project/vcpkg/ports/discordcoreapi/portfile-first-half-new.cmake"  &&
                  sudo bash -c "cat ./DiscordCoreAPI/.github/Raw-Files/portfile-second-half.cmake  >> newFile.txt &&
                  sed -i '1,2d' newFile.txt &&
                  sudo bash -c "cat newFile.txt >> /home/circleci/project/vcpkg/ports/discordcoreapi/portfile-first-half-new.cmake"  &&
                  sudo cp -v -R /home/circleci/project/vcpkg/ports/discordcoreapi/portfile-first-half-new.cmake /home/circleci/project/vcpkg/ports/discordcoreapi/portfile.cmake &&
                  sudo cp -v -R /home/circleci/project/vcpkg/ports/discordcoreapi/portfile-first-half-new.cmake ./DiscordCoreAPI/Vcpkg/ports/discordcoreapi/portfile.cmake &&
                  cd ./DiscordCoreAPI &&
                  sudo git add . &&
                  sudo git commit -m "Updates!" &&
                  sudo git config pull.rebase false &&
                  sudo git pull &&
                  sudo git push origin main &&
                  sudo /home/circleci/project/vcpkg/vcpkg install discordcoreapi:x64-linux
             
      - run:
         name: Update the portfile.
         command: cd vcpkg &&
                  sudo /home/circleci/project/vcpkg/vcpkg install discordcoreapi:x64-linux || true
                
      - run:
         name: Download and install a template-bot.
         command: sudo git clone https://github.com/RealTimeChris/Bot-Template-For-DiscordCoreAPI --depth=1 &&
                  cd Bot-Template-For-DiscordCoreAPI &&
                  sudo apt-get install -y ninja-build &&
                  sudo cmake -S . --preset Linux-Release &&
                  sudo cmake --build --preset Linux-Release &&
                  sudo cmake --install ./Build/Release &&
                  cd "Output Files/Release" &&
                  sudo ./DiscordCoreAPI-Bot-Cpp

  Build-Documentation:
    machine:
        image: ubuntu-2204:2022.04.1
    resource_class: large
    steps:
      - checkout
    
      - add_ssh_keys:
         fingerprints:
             e1:e3:0b:e4:82:48:0e:95:26:dd:aa:25:49:93:92:e7
      
      - run:
           name: Store the public SSH key.
           command: echo $AWS_KEY >> PUBLIC_KEY &&
                    sudo cp ./PUBLIC_KEY /root/.ssh/id_rsa

      - run:
           name: Download and install Doxygen, along with its dependencies.
           command: sudo apt-get update &&
                    sudo git clone https://github.com/doxygen/doxygen &&
                    sudo apt-get install bison &&
                    sudo apt-get install flex &&
                    cd doxygen &&
                    sudo mkdir build &&
                    sudo cmake -G "Unix Makefiles" &&
                    sudo make &&
                    sudo make install &&
                    sudo apt-get install graphviz &&
                    sudo apt-get install openssh-client

      - run:
          name: Collect the original Repo for the docs.
          command: sudo git config --global user.email "40668522+RealTimeChris@users.noreply.github.com" &&
                   sudo git config --global user.name "realtimechris" &&
                   sudo git clone https://realtimechris:${PERSONAL_ACCESS_TOKEN}@github.com/realtimechris/DiscordCoreAPI-Docs --depth=1

      - run:
          name: Collect the documentation and generate it.
          command: sudo git clone https://github.com/RealTimeChris/DiscordCoreAPI --depth=1 &&
                   cd DiscordCoreAPI/Documentation/Doxygen && 
                   sudo doxygen || true

      - run:
          name: Commit and push the docs to the repo.
          command: cd DiscordCoreAPI-Docs && 
                   sudo git add . && 
                   sudo git commit -m "Updates!" && 
                   sudo git push origin main || true

      - run:
          name: Clone the data over to the web server.
          command: ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-144-188-157.us-east-2.compute.amazonaws.com 
                   "cd /var/www && sudo rm -rf discordcoreapi && sudo git clone https://github.com/RealTimeChris/DiscordCoreAPI-Docs --depth=1 ./discordcoreapi"

workflows:
  DiscordCoreAPI:
    jobs:
      - Build-Documentation
      - Build-DiscordCoreAPI
