version: 2.1

jobs:
  Build-Documentation:
    docker:
      - image: cimg/base:edge-22.04
    steps:
      - checkout
    
      - add_ssh_keys:
         fingerprints:
             11:41:70:ff:34:26:dd:e7:6a:c4:cb:8f:07:4c:ce:71
      
      - run:
          name: Collect the original Repo for the docs.
          command: sudo git config --global user.email "40668522+RealTimeChris@users.noreply.github.com " && sudo git config --global user.name "realtimechris" && sudo git clone https://realtimechris:${PERSONAL_ACCESS_TOKEN}@github.com/realtimechris/DiscordCoreAPI-Docs --depth=1

      - run:
          name: Download and install Doxygen.
          command: sudo apt-get update && sudo apt-get install doxygen && sudo apt install graphviz && sudo apt-get install openssh-client && sudo apt remove openssl

      - run:
          name: Collect the documentation and generate it.
          command: sudo git clone https://github.com/RealTimeChris/DiscordCoreAPI --depth=1 && 
                    cd DiscordCoreAPI/Documentation/Doxygen && 
                    sudo doxygen || true

      - run:
          name: Commit and push.
          command: cd DiscordCoreAPI-Docs && 
                   sudo git add . && 
                   sudo git commit -m "Updates!" && 
                   sudo git push origin main || true


      - run:
           name: Collect private key.
           command: echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9n6Gq/yIkBWWiwIQArZjPLxz3Hd9Mwm26Z8VDfQwQOjJtPsnfdF9ziE3zNRS89PmBVFoVPT4fgOVDJ3MQeRB9awHMb0kkMK/glKn2nR1/aqAirxrtVoizRDiarajrUbuiametj3QGDl3A1UPLBaDyPIbfaO8PQfSjNYYMWkBkgpTYFomQrj9VoArwiBbaDbwULXFIPeW73l5uRznYIchjnfVbw+SnI4JyweMr/tTKRc39AjtjLQMuKbJjWp+NaB8iRQqeqFIS3dOHRoYGHwQf1OMYSerjHDFtZQyniu7jBSCB2PeRXsuTca9MQXHoeW3SKq4WL3j0m0staafn2glX" >> PUBLIC_KEY &&
                    sudo mkdir /root/.ssh/ &&
                    sudo cp "./PUBLIC_KEY" "/root/.ssh/id_rsa" &&
                    sudo chmod 600 /root/.ssh/id_rsa

      - run:
          name: Clone the data over to the web server.
          command: ssh -vvv -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@ec2-3-144-188-157.us-east-2.compute.amazonaws.com 
                   "cd /var/www && sudo rm -rf discordcoreapi && sudo git clone https://github.com/RealTimeChris/DiscordCoreAPI-Docs --depth=1 ./discordcoreapi"
            

workflows:
  Build-DiscordCoreAPI:
    jobs:
      - Build-Documentation

