version: 2

jobs:
  build:
    docker:
      - image: "debian:bullseye"
    steps:
      - checkout
      - run:
          name: Installing build dependencies
          command: 'apt-get update && apt-get install -y sudo gcc g++ build-essential git cmake libssl-dev zlib1g-dev'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'
      - run:
          name: Testing installation
          command: 'cmake --build build --target install'
