version: 2.1

jobs:
  Build-Documentation:
    docker:
      - image: cimg/base:edge-22.04
    steps:
      - add_ssh_keys:
          fingerprints:
            c2:79:07:18:78:47:c7:82:a2:99:9f:ad:5c:f0:0e:c5
      - add_ssh_keys:
          fingerprints:
             11:15:d9:bd:d7:76:0d:c0:7b:ff:00:e1:49:91:41:f8

      - checkout 
      - run:
          name: Collect the original Repo for the docs.
          command: sudo git config --global user.email "40668522+RealTimeChris@users.noreply.github.com " && sudo git config --global user.name "realtimechris" && sudo git clone https://realtimechris:${PERSONAL_ACCESS_TOKEN}@github.com/realtimechris/DiscordCoreAPI-Docs --depth=1
      - run:
          name: Download and install Doxygen.
          command: sudo apt-get install doxygen && sudo apt install graphviz && sudo apt-get install openssh-client

      - run:
          name: Collect the documentation and generate it.
          command: sudo git clone https://github.com/RealTimeChris/DiscordCoreAPI --depth=1 && 
                    cd DiscordCoreAPI/Documentation/Doxygen && 
                    sudo doxygen

      - run:
            name: Add AWS to known hosts.
            command: mkdir -p ~/.ssh
                    echo 'ubuntu@ec2-3-144-10-105.us-east-2.compute.amazonaws.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDahSFY9YSPltxMOOkQxT2uuczLsxrXSR6d+0vLtsK4VM+Uzl6TdgffQbJoChJqVYuY7+tHEfDfblB1GPXKiYvqADxHyjRreD+MEdtuuLw0XFZ/Xeaz4Jazwestvcre98Mmo8t2DIztwaZ96RPEiNlKjU33Hih6HwWka4R0+/MQzVU8iw3tI/05qFGJQcSUPse12avZLVyYGANZVH5D6qTjMLMICD73azY59A0HM3zeRlAXrtMKvCUAID8WCaQN+RJQG94xyV9zoeoA+BfUZFMH5v1O83hDsIM75mxcog2jkUezAeUG9DJ/ilFBsFGRa2V7tuGzBGTdJyzVs/+aalAD' > ~/.ssh/known_hosts
                        

      - run:
          name: Commit and push.
          command: cd DiscordCoreAPI-Docs && 
                    sudo git add . && 
                    sudo git commit -m "Updates!" && 
                    sudo git push origin main || true
      - run:
          name: Clone the data over to the web server.
          command: sudo echo -e ${AWS_KEY} >TheRealKey.pem &&
                    sudo ssh -o BatchMode=yes -o StrictHostKeyChecking=no ec2-3-144-10-105.us-east-2.compute.amazonaws.com "uptime" &&
                    sudo ssh -i ${AWS_KEY} ubuntu@ec2-3-144-10-105.us-east-2.compute.amazonaws.com &&
                    cd /var/www &&
                    sudo rm -rf discordcoreapi &&
                    sudo git clone https://github.com/RealTimeChris/DiscordCoreAPI-Docs --depth=1 ./discordcoreapi
            
            

workflows:
  Build-DiscordCoreAPI:
    jobs:
      - Build-Documentation

