version: 2.1

jobs:
  Build-Documentation:
    docker:
      - image: cimg/base:edge-22.04
    steps:
      - add_ssh_keys:
          fingerprints:
            256 SHA256:TNhd8QiQG2hhF5l45TfEwgPyeVIC1v7CzJ2f3UgHfNQ root@ip-172-31-15-191 (ED25519)
      - checkout 

      - run:
           name: Add AWS to known_hosts.
           command: ssh-keyscan -H ec2-3-144-10-105.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
      - run:     
            name: Add AWS to known_hosts
            environment:
                  AWS_PUBLIC_LEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDgWK23FJj9BI3QUzh7R7soYl5hiRAeE9Kkp1ATqRIREBCXIdE0eagjtMYLf1rnjji0oQ9OHk9hWHBkOjWgkEqOfvO+G4ndRxiTzVFb/F5MyLOQoSf/A15+IElan7p8CJHUTfhwe6YwstHxRt8dDBsc8h5RBXSIkx7hcmnsudSIx5YwHFdV2YehdIGBEFjKpnEQ5dwHH3gj99nTmLkT1A2CyP578tkHIAh+qZRa8LGxtcH28R/NHNt2/XoUfKClT4XfMTboTxUDOm3L2SRX1kCn8gkuYpJe5m035L75FDVJpxU14klQuEvB9BBlJTySHWMKOx+YGScUowXRdxLGRS/F"
            command: echo ${AWS_PUBLIC_KEY} >> ~/.ssh/known_hosts
      - run:
          name: Collect the original Repo for the docs.
          command: sudo git config --global user.email "40668522+RealTimeChris@users.noreply.github.com " && sudo git config --global user.name "realtimechris" && sudo git clone https://realtimechris:${PERSONAL_ACCESS_TOKEN}@github.com/realtimechris/DiscordCoreAPI-Docs --depth=1
      - run:
          name: Download and install Doxygen.
          command: sudo apt-get install doxygen && sudo apt install graphviz && sudo apt-get install openssh-client
      - run:
          name: Collect the documentation and generate it.
          command: sudo git clone https://github.com/RealTimeChris/DiscordCoreAPI --depth=1 && 
                    cd DiscordCoreAPI/Documentation/Doxygen && 
                    sudo doxygen
      - run:
          name: commit and push

          command: cd DiscordCoreAPI-Docs && 
                    sudo git add . && 
                    sudo git commit -m "Updates!" && 
                    sudo git push origin main || true
      - run:
          name: Clone the data over to the web server.
          command: sudo echo -e ${AWS_KEY} >TheRealKey.pem && 
                    sudo ssh ubuntu@ec2-3-144-10-105.us-east-2.compute.amazonaws.com -q
            
            
            

workflows:
  Build-DiscordCoreAPI:
    jobs:
      - Build-Documentation

