version: 2.1

jobs:
  Build-Documentation:
    docker:
      - image: cimg/base:edge-22.04
    steps:
      - checkout
    
      - add_ssh_keys:
         fingerprints:
             11:41:70:ff:34:26:dd:e7:6a:c4:cb:8f:07:4c:ce:71
      
      - run:
           name: Download and install Doxygen, graphviz and openssh-client.
           command: sudo apt-get update &&
                   sudo apt-get install doxygen &&
                   sudo apt install graphviz &&
                   sudo apt-get install openssh-client &&
                   sudo apt remove openssl

      - run:
          name: Collect the original Repo for the docs.
          command: sudo git config --global user.email "40668522+RealTimeChris@users.noreply.github.com " &&
                   sudo git config --global user.name "realtimechris" &&
                   sudo git clone https://realtimechris:${PERSONAL_ACCESS_TOKEN}@github.com/realtimechris/DiscordCoreAPI-Docs --depth=1

      - run:
          name: Collect the documentation and generate it.
          command: sudo git clone https://github.com/RealTimeChris/DiscordCoreAPI --depth=1 && 
                   cd DiscordCoreAPI/Documentation/Doxygen && 
                   sudo doxygen || true

      - run:
          name: Commit and push the docs to the repo.
          command: cd DiscordCoreAPI-Docs && 
                   sudo git add . && 
                   sudo git commit -m "Updates!" && 
                   sudo git push origin main || true 
                   
      - run:
           name: Store the public SSH key.
           command: echo $AWS_KEY >> PUBLIC_KEY &&
                    sudo mkdir /root/.ssh/ &&
                    sudo cp "./PUBLIC_KEY" "/root/.ssh/id_rsa" &&
                    sudo chmod 600 /root/.ssh/id_rsa

      - run:
          name: Clone the data over to the web server.
          command: ssh -vvv -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@ec2-3-144-188-157.us-east-2.compute.amazonaws.com 
                   "cd /var/www && sudo rm -rf discordcoreapi && sudo git clone https://github.com/RealTimeChris/DiscordCoreAPI-Docs --depth=1 ./discordcoreapi"
            

workflows:
  Build-DiscordCoreAPI:
    jobs:
      - Build-Documentation

