version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:edge-22.04

    steps:
      - checkout
      - run:
          name: Installing vcpkg.
          command: 'sudo git clone https://github.com/Microsoft/vcpkg ./vcpkg && cd ./vcpkg && sudo ./bootstrap-vcpkg.sh'
      - run:
          name: Installing dependencies.
          command: 'sudo apt-get install nasm && sudo apt-get install bison  && cd ./vcpkg && sudo ./vcpkg install libsodium:x64-linux && sudo ./vcpkg install opus:x64-linux && sudo ./vcpkg install nlohmann-json:x64-linux && sudo ./vcpkg install openssl:x64-linux && sudo ./vcpkg install  ffmpeg:x64-linux'
      - run:
          name: Creating build files.
          command: 'cd ./vcpkg && cmake -S . -B ./Build -D_VCPKG_INSTALLED_DIR=./installed/x64-linux'
