version: 2.1

jobs:
  Build-Documentation:
    docker:
      - image: cimg/base:edge-22.04
    steps:
      - add_ssh_keys:
          fingerprints:
            PxLXxAtrWtn1X/uWvNkBJmAqmGkAK5IfkhmuY9/rAyo
      - checkout 
      - run:
          name: Checkout github pages repository
          command: git config --global user.email "40668522+RealTimeChris@users.noreply.github.com" && git config --global user.name "realtimechris"
      - run:
          name: Download and install Doxygen.
          command: sudo apt-get install doxygen && sudo apt install graphviz
      - run:
          name: Collect the original Repo for the docs.
          command: git clone https://github.com/RealTimeChris/DiscordCoreAPI-Docs
      - run:
          name: Collect the documentation and generate it.
          command: |
            sudo git clone https://github.com/RealTimeChris/DiscordCoreAPI --depth=1
            cd DiscordCoreAPI/Documentation/Doxygen
            sudo doxygen
      - run:
          name: commit and push
          command: | 
            cd DiscordCoreAPI-Docs
            sudo git config --global user.email "40668522+RealTimeChris@users.noreply.github.com"
            sudo git config --global user.name "realtimechris"
            sudo git config --global --add safe.directory /home/circleci/project/DiscordCoreAPI-Docs
            sudo git add .
            sudo git commit -m "Updates!"
            #sudo git push origin main
      - run:
          name: Clone the data over to the web server.
          command: |
            sudo echo ${AWS_KEY} >TheRealKey.pem
            dir
            ssh -i "./TheRealKey.pem" ubuntu@ec2-3-144-10-105.us-east-2.compute.amazonaws.com
            cd /var/www
            sudo rm -rf discordcoreapi
            sudo git clone https://github.com/RealTimeChris/DiscordCoreAPI-Docs --depth=1 ./discordcoreapi

workflows:
  Build-DiscordCoreAPI:
    jobs:
      - Build-Documentation

