version: 2.1

orbs: 
  cmake: sensu/cmake@1.0.0


jobs:
  build:
    docker:
      - image: cimg/base:2022.06

    steps:
      - checkout
      - run:
          name: Install CMAKE
          command: sudo apt list --all-versions cmake

      - run:
          name: Installing build dependencies
          command: 'sudo apt-get update && sudo apt-get install -y sudo gcc g++ build-essential sudo git cmake libssl-dev zlib1g-dev'
      - run:
          name: Creating Build Files
          command: 'cmake -S . -B ./Build'
      - run:
          name: Creating Binary Files
          command: 'cmake --build --preset Linux-Release'
