version: 2.1

orbs: 
  cmake: sensu/cmake@1.0.0


jobs:
  build:
    machine:
      image: ubuntu-2004:2022.04.2

    steps:
      - checkout
      - cmake/install:
        version: "3.20"
      - run:
          name: Installing build dependencies
          command: 'sudo apt-get update && apt-get install -y sudo gcc g++ build-essential git cmake libssl-dev zlib1g-dev'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'
      - run:
          name: Testing installation
          command: 'cmake --build build --target install'
