version: 2.1

jobs:
  Build-Documentation:
    docker:
      - image: cimg/base:edge-22.04
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
             c2:79:07:18:78:47:c7:82:a2:99:9f:ad:5c:f0:0e:c5
      
      - run:
          name: Collect the original Repo for the docs.
          command: sudo git config --global user.email "40668522+RealTimeChris@users.noreply.github.com " && sudo git config --global user.name "realtimechris" && sudo git clone https://realtimechris:${PERSONAL_ACCESS_TOKEN}@github.com/realtimechris/DiscordCoreAPI-Docs --depth=1

      - run:
          name: Download and install Doxygen.
          command: sudo apt-get install doxygen && sudo apt install graphviz && sudo apt-get install ssh

      - run:
          name: Collect the documentation and generate it.
          command: sudo git clone https://github.com/RealTimeChris/DiscordCoreAPI --depth=1 && 
                    cd DiscordCoreAPI/Documentation/Doxygen && 
                    sudo doxygen || true

      - run:
          name: Commit and push.
          command: cd DiscordCoreAPI-Docs && 
                   sudo git add . && 
                   sudo git commit -m "Updates!" && 
                   sudo git push origin main || true

      - run:
          name: Clone the data over to the web server.
          command: cd /home/circleci/.ssh &&
                   sudo echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFrMt+Vwx6pRaaPz3fL2o9sYiY/Y0egtHhZO6jBqnZBC 40668522+RealTimeChris@users.noreply.github.com" >> authorized_keys &&
                   dir &&
                   cat id_rsa.pub &&
                   sudo echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFrMt+Vwx6pRaaPz3fL2o9sYiY/Y0egtHhZO6jBqnZBC 40668522+RealTimeChris@users.noreply.github.com" >> PUBLIC_KEY.pem.pub &&
                   cat PUBLIC_KEY.pem.pub &&
                   sudo ssh -i PUBLIC_KEY.pem.pub -o BatchMode=yes -o StrictHostKeyChecking=no ec2-3-144-188-157.us-east-2.compute.amazonaws.com &&
                   cd /var/www &&
                   sudo rm -rf discordcoreapi &&
                   sudo git clone https://github.com/RealTimeChris/DiscordCoreAPI-Docs --depth=1 ./discordcoreapi
            

workflows:
  Build-DiscordCoreAPI:
    jobs:
      - Build-Documentation

