version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:edge-22.04
    resource_class: large
    steps:
      - checkout
      - run:
          name: Installing vcpkg.
          command: 'sudo git clone https://github.com/Microsoft/vcpkg ./vcpkg && cd ./vcpkg && sudo ./bootstrap-vcpkg.sh'
      - run:
          name: Copying over Vcpkg files.
          command: 'sudo cp -a -v Vcpkg/* vcpkg'
      - run:
          name: Installing the library and its dependencies.
          command: 'sudo apt-get install -y ninja-build && sudo apt-get install nasm && sudo apt-get install bison  && cd ./vcpkg && sudo ./vcpkg install discordcoreapi:x64-linux'
      - run:
         name: Download and test the Bot-Template.
         command: 'git clone https://github.com/RealTimeChris/Bot-Template-For-DiscordCoreAPI ./TestBot && cd TestBot && cmake -S . --preset Linux-Release && cmake --build --preset Linux-Release && cmake --install ./Build/Release && cd "Output Files\Release" && ./DiscordCoreAPI-Bot-Cpp'
      
