version: 2.1

jobs:
  Build-Documentation:
    docker:
      - image: cimg/base:edge-22.04
    steps:
      - add_ssh_keys:
          fingerprints:
            b0:3e:e3:7c:b9:68:ca:ba:9a:c6:31:13:56:70:cf:ad
      - add_ssh_keys:
          fingerprints:
            c2:79:07:18:78:47:c7:82:a2:99:9f:ad:5c:f0:0e:c5
            
      - checkout 
      - run:
          name: Collect the original Repo for the docs.
          command: sudo git config --global user.email "40668522+RealTimeChris@users.noreply.github.com " && sudo git config --global user.name "realtimechris" && sudo git clone https://realtimechris:${PERSONAL_ACCESS_TOKEN}@github.com/realtimechris/DiscordCoreAPI-Docs --depth=1
      - run:
          name: Download and install Doxygen.
          command: sudo apt-get install doxygen && sudo apt install graphviz && sudo apt-get install openssh-client
      - run:
           name: Add AWS to known_hosts
           command: sudo ssh-keyscan -H ec2-3-144-10-105.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts

      - run:
          name: Collect the documentation and generate it.
          command: sudo git clone https://github.com/RealTimeChris/DiscordCoreAPI --depth=1 && 
                    cd DiscordCoreAPI/Documentation/Doxygen && 
                    sudo doxygen
      - run:
          name: Commit and push.
          command: cd DiscordCoreAPI-Docs && 
                    sudo git add . && 
                    sudo git commit -m "Updates!" && 
                    sudo git push origin main || true
      - run:
          name: Clone the data over to the web server.
          command: sudo echo -e ${AWS_KEY} >TheRealKey.pem &&
                    sudo ssh -o BatchMode=yes -o StrictHostKeyChecking=no ubuntu@ec2-3-144-10-105.us-east-2.compute.amazonaws.com "uptime"
                    sudo ssh -i TheRealKey.pem ubuntu@ec2-3-144-10-105.us-east-2.compute.amazonaws.com &&
                    cd /var/www &&
                    sudo rm -rf discordcoreapi &&
                    sudo git clone https://github.com/RealTimeChris/DiscordCoreAPI-Docs --depth=1 ./discordcoreapi
            
            

workflows:
  Build-DiscordCoreAPI:
    jobs:
      - Build-Documentation

