name: Prepare release for VCPKG

on:
  push:


jobs:
  Collect-Vcpkg-Info:
    runs-on: ubuntu-22.04
    steps:

         - name: Update vcpkg and install other dependencies.
           run: |
                sudo apt-get install nasm &&
                cd /usr/local/share/vcpkg &&
                sudo ./bootstrap-vcpkg.sh &&
                sudo git stash &&
                sudo git pull &&
                sudo vcpkg update

         - name: Collect the repo.
           run: |   
                sudo git config --global user.email "40668522+RealTimeChris@users.noreply.github.com"
                sudo git config --global user.name "realtimechris"
                sudo git clone https://realtimechris:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/realtimechris/DiscordCoreAPI.git ./DiscordCoreAPI --depth=1

         - name: Construct the original portfile and version file.
           run: |
                cd ./discordcoreapi &&
                sudo touch ./CMake/Raw-Files/Portfile-The-First.cmake &&
                sudo touch ./CMake/Raw-Files/Portfile-The-Second.cmake &&
                sudo touch ./vcpkg/ports/discordcoreapi/vcpkg.json &&
                sudo bash -c "cat ./CMake/Raw-Files/Top-Of-Portfile.cmake >> ./CMake/Raw-Files/Portfile-The-First.cmake" &&
                sudo git rev-parse HEAD | sudo tee ./CMake/Raw-Files/Portfile-The-First.cmake -a &&
                sudo bash -c "cat ./CMake/Raw-Files/Middle-Of-Portfile.cmake >> ./CMake/Raw-Files/Portfile-The-First.cmake" &&
                sudo bash -c "echo $'0' >> ./CMake/Raw-Files/Portfile-The-First.cmake" &&
                sudo bash -c "cat ./CMake/Raw-Files/Bottom-Of-Portfile.cmake >> ./CMake/Raw-Files/Portfile-The-First.cmake" &&
                sudo bash -c "cat ./CMake/Raw-Files/Top-Of-Version-File.txt > ./vcpkg/ports/discordcoreapi/vcpkg.json" &&
                sudo truncate -s -1 ./vcpkg/ports/discordcoreapi/vcpkg.json &&
                sudo bash -c "cat ./CMake/Raw-Files/Bottom-Of-Version-File.txt >> ./vcpkg/ports/discordcoreapi/vcpkg.json"

         - name: Attempt to install the library, to collect the SHA512 value.
           run: |
                cd ./discordcoreapi &&
                sudo mkdir /usr/local/share/vcpkg/ports/discordcoreapi/ &&
                [ -f /usr/local/share/vcpkg/ports/discordcoreapi/vcpkg.json ] && echo "File exists." || sudo cp -v -R ./vcpkg/ports/discordcoreapi/vcpkg.json /usr/local/share/vcpkg/ports/discordcoreapi/vcpkg.json  &&
                sudo cp -v -R ./CMake/Raw-Files/Portfile-The-First.cmake /usr/local/share/vcpkg/ports/discordcoreapi/portfile.cmake &&
                sudo /usr/local/share/vcpkg/vcpkg install discordcoreapi:x64-linux | sudo tee InstallOutput.txt || true

         - name:  Update the portfile and download/install the library.
           run: |
                cd ./discordcoreapi &&
                sudo sed -i '/Actual hash/,$!d' InstallOutput.txt &&
                sudo sed -i 's/^.....................//' InstallOutput.txt &&
                sudo sed -i '2,250d' InstallOutput.txt &&
                sudo truncate -s -3 InstallOutput.txt &&
                sudo bash -c "cat ./CMake/Raw-Files/Top-Of-Portfile.cmake >> ./CMake/Raw-Files/Portfile-The-Second.cmake" &&
                sudo git rev-parse HEAD | sudo tee ./CMake/Raw-Files/Portfile-The-Second.cmake -a &&
                sudo bash -c "cat ./CMake/Raw-Files/Middle-Of-Portfile.cmake >> ./CMake/Raw-Files/Portfile-The-Second.cmake" &&
                sudo bash -c "cat InstallOutput.txt >> ./CMake/Raw-Files/Portfile-The-Second.cmake" &&
                sudo bash -c "echo $'' >> ./CMake/Raw-Files/Portfile-The-Second.cmake" &&
                sudo bash -c "cat ./CMake/Raw-Files/Bottom-Of-Portfile.cmake >> ./CMake/Raw-Files/Portfile-The-Second.cmake" &&
                sudo touch ./vcpkg/ports/discordcoreapi/portfile.cmake &&
                sudo cp -v -R ./CMake/Raw-Files/Portfile-The-Second.cmake /usr/local/share/vcpkg/ports/discordcoreapi/portfile.cmake &&
                sudo cp -v -R ./CMake/Raw-Files/Portfile-The-Second.cmake ./vcpkg/ports/discordcoreapi/portfile.cmake &&
                sudo cp -v -R ./vcpkg/ports/* /usr/local/share/vcpkg/ports/ &&
                cd /usr/local/share/vcpkg &&
                sudo ./vcpkg format-manifest ./ports/discordcoreapi/vcpkg.json &&
                sudo git add . &&
                sudo git commit -m "[bot] VCPKG info update"  &&
                cat /usr/local/share/vcpkg/versions/d-/discordcoreapi.json && 
                sudo /usr/local/share/vcpkg/vcpkg x-add-version discordcoreapi &&
                cd /home/runner/work/DiscordCoreAPI/DiscordCoreAPI/discordcoreapi &&
                sudo cp -v -R /usr/local/share/vcpkg/ports/discordcoreapi/vcpkg.json ./vcpkg/ports/discordcoreapi/vcpkg.json &&
                sudo cp -v -R /usr/local/share/vcpkg/versions/baseline.json ./vcpkg/versions/baseline.json &&
                sudo cp -v -R /usr/local/share/vcpkg/versions/d-/discordcoreapi.json ./vcpkg/versions/d-/discordcoreapi.json &&
                cat ./vcpkg/versions/d-/discordcoreapi.json &&
                sudo rm -rf InstallOutput.txt &&
                sudo rm -rf ./CMake/Raw-Files/Portfile-The-First.cmake &&
                sudo rm -rf ./CMake/Raw-Files/Portfile-The-Second.cmake &&
                sudo git add . &&
                sudo git commit -m "[bot] VCPKG info update [skip ci]" &&
                sudo git config pull.rebase false &&
                sudo git pull &&
                sudo git push origin master &&
                sudo /usr/local/share/vcpkg/vcpkg install discordcoreapi:x64-linux