name: Build-DiscordCoreAPI
on:
  push:

jobs:
  Build-It:
    runs-on: ubuntu-20.04
    steps:
         - name: Download and install vcpkg as well as other dependencies.
           run: sudo apt-get install nasm && 
                sudo git clone https://github.com/Microsoft/vcpkg --depth=1 &&
                sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && 
                sudo apt install -y g++-11 &&
                cd vcpkg &&
                sudo ./bootstrap-vcpkg.sh

         - name: Copy over the current portfile.
           run: sudo git clone https://github.com/RealTimeChris/DiscordCoreAPI --depth=1

         - name: Update the portfile.
           run: sudo chmod 600 ./DiscordCoreAPI/Vcpkg/ports/discordcoreapi/portfile.cmake 
         - name: Update the portfile.
           run: dir ./DiscordCoreAPI &&
                sudo bash -c "cat ./DiscordCoreAPI/.github/Raw-Files/portfile-first-half.cmake > ./DiscordCoreAPI/Vcpkg/ports/discordcoreapi/portfile.cmake"
         - name: Update the portfile.
           run: cd DiscordCoreAPI &&
                sudo git rev-parse HEAD | sudo tee ./Vcpkg/ports/discordcoreapi/portfile.cmake -a
         - name: Update the portfile.
           run: sudo bash -c "cat ./DiscordCoreAPI/.github/Raw-Files/portfile-second-half.cmake >> ./DiscordCoreAPI/Vcpkg/ports/discordcoreapi/portfile.cmake" &&
                sudo cat ./DiscordCoreAPI/Vcpkg/ports/discordcoreapi/portfile.cmake &&
                sudo cp -v -R ./DiscordCoreAPI/Vcpkg/* /usr/local/share/vcpkg &&
                sudo vcpkg install discordcoreapi:x64-linux --overlay-ports=../
             
         - name: Download and install DiscordCoreAPI
           run: cd vcpkg &&
                sudo ./vcpkg install discordcoreapi:x64-linux || true &&
                cat /home/runner/work/DiscordCoreAPI/DiscordCoreAPI/vcpkg/buildtrees/discordcoreapi/install-x64-linux-dbg-out.log
                
         - name: Download and install a template-bot.
           run: sudo git clone https://github.com/RealTimeChris/Bot-Template-For-DiscordCoreAPI --depth=1 &&
                cd Bot-Template-For-DiscordCoreAPI &&
                sudo apt-get install -y ninja-build &&
                sudo cmake -S . --preset Linux-Release &&
                sudo cmake --build --preset Linux-Release &&
                sudo cmake --install ./Build/Release &&
                cd "Output Files/Release" &&
                sudo ./DiscordCoreAPI-Bot-Cpp
