name: Build-DiscordCoreAPI
on:
  push:

jobs:
  Build-It:
    runs-on: ubuntu-20.04
    steps:
         - name: Download and install vcpkg as well as other dependencies.
           run: sudo apt-get install nasm && 
                sudo git clone https://github.com/Microsoft/vcpkg --depth=1 &&
                sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && 
                sudo apt install -y g++-11 &&
                cd vcpkg &&
                sudo ./bootstrap-vcpkg.sh

         - name: Copy over the current portfile.
           run: sudo git clone https://github.com/RealTimeChris/DiscordCoreAPI --depth=1

         - name: Update the portfile.
           run: sudo chmod 600 ./DiscordCoreAPI/Vcpkg/ports/discordcoreapi/portfile.cmake

         - name: Update the portfile.
           run: sudo bash -c "cat ./DiscordCoreAPI/.github/Raw-Files/portfile-first-half.cmake > ./DiscordCoreAPI/Vcpkg/ports/discordcoreapi/portfile.cmake"

         - name: Update the portfile.
           run: cd DiscordCoreAPI &&
                sudo git rev-parse HEAD | sudo tee ./Vcpkg/ports/discordcoreapi/portfile.cmake -a

         - name: Update the portfile.
           run: sudo bash -c "cat ./DiscordCoreAPI/.github/Raw-Files/portfile-second-half.cmake >> ./DiscordCoreAPI/Vcpkg/ports/discordcoreapi/portfile.cmake" &&
                sudo cat ./DiscordCoreAPI/Vcpkg/ports/discordcoreapi/portfile.cmake &&
                sudo cp -v -R ./DiscordCoreAPI/Vcpkg/* /usr/local/share/vcpkg &&
                sudo /usr/local/share/vcpkg/vcpkg install discordcoreapi:x64-linux --overlay-ports=./DiscordCoreAPI/Vcpkg/ports | sudo tee InstallOutput.txt &&
                sed -i '/Actual hash/,$!d' InstallOutput.txt &&
                sed -i 's/^.....................//' InstallOutput.txt &&
                sed -i '2,250d' InstallOutput.txt &&
                truncate -s -3 InstallOutput.txt &&
                sudo bash -c "head -c 241 ./DiscordCoreAPI/Vcpkg/ports/discordcoreapi/portfile.cmake > ./DiscordCoreAPI/.github/Raw-Files/portfile-first-half.cmake"  &&
                sudo bash -c "cat InstallOutput.txt >> ./DiscordCoreAPI/.github/Raw-Files/portfile-first-half.cmake"  &&
                sudo bash -c "cat ./DiscordCoreAPI/.github/Raw-Files/portfile-second-half.cmake  >> ./DiscordCoreAPI/.github/Raw-Files/portfile-first-half.cmake"  &&
                sudo cp -v -R ./DiscordCoreAPI/.github/Raw-Files/portfile-first-half.cmake /usr/local/share/vcpkg/ports/discordcoreapi/portfile.cmake &&
                sudo cp -v -R ./DiscordCoreAPI/.github/Raw-Files/portfile-first-half.cmake ./DiscordCoreAPI/Vcpkg/ports/discordcoreapi/portfile.cmake &&
                cd ./DiscordCoreAPI &&
                git add . &&
                git commit -m "Updates!" &&
                git push origin main
             
         - name: Update the portfile.
           run: cd vcpkg &&
                sudo /usr/local/share/vcpkg/vcpkg install discordcoreapi:x64-linux || true &&
                cat /home/runner/work/DiscordCoreAPI/DiscordCoreAPI/vcpkg/buildtrees/discordcoreapi/install-x64-linux-dbg-out.log
                
         - name: Download and install a template-bot.
           run: sudo git clone https://github.com/RealTimeChris/Bot-Template-For-DiscordCoreAPI --depth=1 &&
                cd Bot-Template-For-DiscordCoreAPI &&
                sudo apt-get install -y ninja-build &&
                sudo cmake -S . --preset Linux-Release &&
                sudo cmake --build --preset Linux-Release &&
                sudo cmake --install ./Build/Release &&
                cd "Output Files/Release" &&
                sudo ./DiscordCoreAPI-Bot-Cpp
