
name: Build-and-Test-CLANG-MacOS

on:
  push:
    branches:
    - main
    - dev


jobs:
  Build:
    runs-on: macos-latest
    
    strategy:
      fail-fast: false
      matrix:
        clang: [16]
        build_type: [Debug, Release]
        std: [20]

    steps:
    - uses: actions/checkout@v3

    - name: Update Vcpkg and install other dependencies.
      run: |
            cd /usr/local/share/vcpkg
            ./bootstrap-vcpkg.sh
            git stash
            git pull
            vcpkg update

    - name: Install Clang17
      run: |
            brew install llvm
            echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> ~/.bash_profile
            export LDFLAGS="-L/usr/local/opt/llvm/lib"
            export CPPFLAGS="-I/usr/local/opt/llvm/include"

    - name: Copy the Jsonifier repo over.
      run: |
           sudo git clone https://github.com/RealTimeChris/Jsonifier
           sudo cp -r -v ./Jsonifier/Vcpkg/* /usr/local/share/vcpkg/

    - name: Install the dependencies.
      run: |
           vcpkg install jsonifier:x64-osx
           vcpkg install opus:x64-osx
           vcpkg install libsodium:x64-osx
           vcpkg install openssl:x64-osx

    - name: Configure CMake
      working-directory: Tests
      run: |
           cmake -S . -B ./Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang-16 -DGITHUB_BRANCH_TYPE=${{github.ref}}

    - name: Build the Test
      working-directory: Tests/Build
      run: |
           cmake --build . --config=${{matrix.build_type}}

    - name: Install the Test
      working-directory: Tests/Build
      run: |
           cmake --install ./ --config=${{matrix.build_type}}

    - name: Run the Test
      working-directory: Tests/Install/${{matrix.build_type}}
      run: |
            chmod u+x ./DiscordCoreAPITest
            ./DiscordCoreAPITest
      continue-on-error: true
      