name: Build-and-Test-CLANG-Ubuntu

on:
  push:
    branches:
    - main
    - dev

jobs:
  Build:
    runs-on: ubuntu-22.04
    
    strategy:
      fail-fast: false
      matrix:
        clang: [18]
        build_type: [Debug, Release]
        std: [20]

    steps:
    - uses: actions/checkout@v3
  
    - name: Install the latest Clang compiler.
      working-directory: ./
      run:  |
            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh
            sudo ./llvm.sh 18

    - name: Update Vcpkg and install other dependencies.
      run: | 
            sudo apt-get update --fix-missing
            sudo apt-get upgrade --fix-missing
            sudo apt-get install nasm
            cd /usr/local/share/vcpkg
            ./bootstrap-vcpkg.sh
            git stash
            git pull
            vcpkg update

    - name: Install the dependencies.
      run: |
           vcpkg install opus:x64-linux
           vcpkg install libsodium:x64-linux
           vcpkg install openssl:x64-linux

    - name: Configure CMake
      working-directory: ./
      run: |
           cmake -S . -B ./Build -DCMAKE_CXX_COMPILER=/usr/bin/clang++-18 -DDEV=true -DDISCORDCOREAPI_TEST=true -DVCPKG_ROOT_DIR=/usr/local/share/vcpkg

    - name: Build the Test
      working-directory: ./Build
      run: |
           cmake --build . --config=${{matrix.build_type}}

    - name: Run the Test
      working-directory: ./Build/Tests
      run: |
            chmod u+x ./DiscordCoreAPITest
            ./DiscordCoreAPITest
      continue-on-error: true