
name: Build Documentation.
on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
        - name: Store the public SSH key.
          run: echo "${{ secrets.AWS_KEY }}" >> PUBLIC_KEY
        - name: Copy the SSH key.
          run: sudo cp ./PUBLIC_KEY /root/.ssh/id_rsa &&
               sudo chmod 600 /root/.ssh/id_rsa

        - name: Download and install Doxygen, along with its dependencies.
          run: sudo apt-get update &&
             sudo git clone https://github.com/doxygen/doxygen &&
             sudo apt-get install bison &&
             sudo apt-get install flex &&
             sudo apt-get install doxygen &&
             cd doxygen &&
             sudo apt-get install graphviz &&
             sudo apt-get install openssh-client &&
             sudo apt-get install ssh
             #sudo mkdir build &&
             #sudo cmake -G "Unix Makefiles" &&
             #sudo make &&
             #sudo make install &&
             
        - name: Collect the original Repo for the docs.
          run: sudo git config --global user.email "40668522+RealTimeChris@users.noreply.github.com" &&
               sudo git config --global user.name "realtimechris" &&
               sudo git clone https://realtimechris:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/realtimechris/DiscordCoreAPI-Docs --depth=1

        - name: Collect the documentation and generate it.
          run: sudo git clone https://github.com/RealTimeChris/DiscordCoreAPI --depth=1 &&
                cd DiscordCoreAPI/Documentation/Doxygen && 
                sudo doxygen || true
                
        - name: Commit and push the docs to the repo.
          run: cd DiscordCoreAPI-Docs && 
                   sudo git add . && 
                   sudo git commit -m "Updates!" && 
                   sudo git push origin main || true

        - name: Clone the data over to the web server.
          run: sudo ssh -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@ec2-3-144-188-157.us-east-2.compute.amazonaws.com 
                   "cd /var/www && sudo rm -rf discordcoreapi && sudo git clone https://github.com/RealTimeChris/DiscordCoreAPI-Docs --depth=1 ./discordcoreapi"
