name: Build-and-Test-GCC-Ubuntu

on:
  push:
    branches:
    - main
    - dev

jobs:
  Build:
    runs-on: ubuntu-22.04
    
    strategy:
      fail-fast: false
      matrix:
        gcc: [12]
        build_type: [Debug, Release]
        std: [20]
    env:
      CC: gcc-${{matrix.gcc}}
      CXX: g++-${{matrix.gcc}}

    steps:
    - uses: actions/checkout@v3

    - name: Update Vcpkg and install other dependencies.
      run: | 
            sudo apt-get update --fix-missing
            sudo apt-get upgrade --fix-missing
            sudo apt-get install nasm
            cd /usr/local/share/vcpkg
            ./bootstrap-vcpkg.sh
            git stash
            git pull
            vcpkg update

    - name: Copy the Jsonifier repo over.
      run: |
           sudo git clone https://github.com/RealTimeChris/Jsonifier
           sudo cp -r -v ./Jsonifier/Vcpkg/* /usr/local/share/vcpkg/

    - name: Install the dependencies.
      run: |
           vcpkg install jsonifier:x64-linux
           vcpkg install opus:x64-linux
           vcpkg install libsodium:x64-linux
           vcpkg install openssl:x64-linux

    - name: Configure CMake
      working-directory: Tests
      run: |
           cmake -S . -B ./Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DGITHUB_BRANCH_TYPE=${{github.ref}}

    - name: Build the Test
      working-directory: Tests/Build
      run: |
           cmake --build . --config=${{matrix.build_type}}

    - name: Install the Test
      working-directory: Tests/Build
      run: |
           cmake --install ./ --config=${{matrix.build_type}}

    - name: Run the Test
      working-directory: Tests/Install/${{matrix.build_type}}
      run: |
            chmod u+x ./DiscordCoreAPITest
            ./DiscordCoreAPITest
      continue-on-error: true