name: Build-and-Test-GCC-MacOS

on:
  push:
    branches:
    - main
    - dev

jobs:
  Build:
    runs-on: macos-latest
    
    strategy:
      fail-fast: false
      matrix:
        gcc: [13]
        build_type: [Debug, Release]
        std: [20]

    steps:
    - uses: actions/checkout@v3

    - name: Install the latest g++ compiler.
      run: |
            brew install gcc

    - name: Install the dependencies.
      run: |
           vcpkg install opus:x64-osx
           vcpkg install libsodium:x64-osx
           vcpkg install openssl:x64-osx

    - name: Configure CMake
      working-directory: ./
      run: |
           cmake -S . -B ./Build -DCMAKE_CXX_COMPILER=/usr/local/opt/gcc@13/bin/g++-13 -DDEV=true  -DDISCORDCOREAPI_TEST=true -DVCPKG_ROOT_DIR=/usr/local/share/vcpkg

    - name: Build the Test
      working-directory: ./Build
      run: |
           cmake --build . --config=${{matrix.build_type}}

    - name: Run the Test
      working-directory: ./Build/Tests
      run: |
            chmod u+x ./DiscordCoreAPITest
            ./DiscordCoreAPITest
      continue-on-error: true