# This is a basic workflow to help you get started with Actions

name: DiscordCoreAPI CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build-Linux-x64:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install vcpkg and some other dependencies.
        run: | 
          sudo apt-get install nasm
          sudo apt-get install bison
          sudo git clone https://github.com/Microsoft/vcpkg
          cd ./vcpkg
          sudo ./bootstrap-vcpkg.sh
          sudo cp -a -v $GITHUB_WORKSPACE/Vcpkg/* /usr/local/share/vcpkg/
          cd ..
          sudo apt-get install -y ninja-build
          vcpkg install discordcoreapi:x64-linux
          
          # This workflow contains a single job called "build"
  Build-Windows-x64:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install vcpkg and some other dependencies.
        run: |
          git clone https://github.com/Microsoft/vcpkg ./vcpkg2
          cd ./vcpkg
          dir
          ./bootstrap-vcpkg.bat
          cd ..
          cp -a -v $GITHUB_WORKSPACE/Vcpkg/* ./vcpkg2/
          cd ..
          vcpkg install discordcoreapi:x64-linux
