name: Build-and-Test-MSVC-Windows

on:
  push:
    branches:
    - main
    - dev

jobs:
  Build:
    runs-on: windows-latest
    
    strategy:
      fail-fast: false
      matrix:
        msvc: [2022]
        build_type: [Debug, Release]
        std: [20]

    steps:
    - uses: actions/checkout@v3

    - name: Update Vcpkg and install other dependencies.
      run: | 
            cd C:/vcpkg
            ./bootstrap-vcpkg.bat
            git stash
            git pull
            vcpkg update
           
    - name: Install the dependencies.
      run: |
           vcpkg install opus:x64-windows
           vcpkg install libsodium:x64-windows
           vcpkg install openssl:x64-windows

    - name: Configure CMake
      working-directory: ./
      run: |
           cmake -S . -B ./Build -DDEV=true -DDISCORDCOREAPI_TEST=true -DVCPKG_ROOT_DIR=C:/vcpkg

    - name: Build the Test
      working-directory: ./Build
      run: |
           cmake --build . --config=${{matrix.build_type}}

    - name: Install the Test
      working-directory: ./Build/Tests
      run: |
           cmake --install ./ --config=${{matrix.build_type}}

    - name: Run the Test
      working-directory: ./Tests/Install/${{matrix.build_type}}
      run: |
            ./DiscordCoreAPITest.exe
      continue-on-error: true